name: Request PR Review
run-name: Request PR Review
on:
  pull_request_target:
    types: [labeled]



jobs:
  lets-send-a-slack:
    if: ${{github.event.label.name == 'Needs Review'}}
    runs-on: ubuntu-latest
    environment: pr
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # with:
        #   files: '**.pw.ts'
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file"
          done
        # with: 
        #   fetch-depth: 2
      # - id: DIFF
      #   name: Run Diff
      #   run: git diff --name-only master..${{ github.event.pull_request.head.sha }}
        #run: echo "files=$(git diff --name-only --diff-filter=ACMRT origin/master...origin/pr-test | xargs)" >> "$GITHUB_OUTPUT"
        # run: echo "files=$(git diff --name-only  master...HEAD)" >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v6
        env:
          SLACK_WEBHOOK_PATH: ${{ secrets.SLACK_WEBHOOK_PATH }}
          DIFF: ${{ toJSON(steps.changed-files.outputs.all_changed_files) }}
        with:
          script: require('.github/scripts/pr-onLabeled.js')({github, context}, ${{toJSON(steps.changed-files.outputs.all_changed_files)}})

