name: Request PR Review
run-name: Request PR Review
on:
  pull_request_target:
    types: [labeled]

jobs:
  lets-send-a-slack:
    if: ${{github.event.label.name == 'Needs Review'}}
    runs-on: ubuntu-latest
    environment: pr
    steps:
      - id: checkout
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2
      - id: DIFF
        run: git diff --name-only -r HEAD^1 HEAD >> $GITHUB_OUTPUT
      - id: script
      - uses: actions/github-script@v6
        env:
          SLACK_WEBHOOK_PATH: ${{ secrets.SLACK_WEBHOOK_PATH }}
          DIFF: ${{ toJSON(steps.DIFF.outputs) }}
        with:
          script: require('.github/scripts/pr-onLabeled.js')({github, context})

