name: Request PR Review
run-name: Request PR Review
on:
  pull_request_target:
    types: [labeled]



jobs:
  lets-send-a-slack:
    if: ${{github.event.label.name == 'Needs Review'}}
    runs-on: ubuntu-latest
    environment: pr
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2
      - id: DIFF
        name: Run Diff
        run: echo "files=$(git diff --name-only  master...HEAD)" >> "$GITHUB_OUTPUT" |
          git diff --name-only  master...HEAD
      - uses: actions/github-script@v6
        env:
          SLACK_WEBHOOK_PATH: ${{ secrets.SLACK_WEBHOOK_PATH }}
          DIFF: ${{ toJSON(steps.DIFF.outputs.files) }}
        with:
          script: require('.github/scripts/pr-onLabeled.js')({github, context}, ${{steps.DIFF.outputs.files}})

