name: Pull Request Messenger
on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('test')

            var msg = `👋 Thanks for participating! I will review as soon as possible, usually within a few hours.
