name: Pull Request Messenger
on:
  pull_request_target:
    types: [labeled]

jobs:
  comment:
    # if: ${{github.label.name == 'bug'}}
    runs-on: ubuntu-latest
    steps:
      - name: get context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - uses: actions/checkout@v2
      # - uses: actions/github-script@v6
      #   with:
      #     script: require('.github/scripts/setup-pr.js')({github, context, core})
