name: Request PR Review
run-name: Request PR Review
on:
  pull_request_target:
    types: [labeled]

jobs:
  lets-send-a-slack:
    if: ${{github.event.label.name == 'Needs Review'}}
    runs-on: ubuntu-latest
    environment: pr
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          SLACK_WEBHOOK_PATH: ${{ secrets.SLACK_WEBHOOK_PATH }}
        with:
          script: require('.github/scripts/labeled-pr.js')({github, context})
