name: Pull Request Messenger
on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: require('./scripts/setup-pr.js')({github, context})
