name: Request PR Review
run-name: Request PR Review
on:
  pull_request_target:
    types: [labeled]

jobs:
  lets-send-a-slack:
    if: ${{github.event.label.name == 'Needs Review'}}
    runs-on: ubuntu-latest
    steps:
      with:
        super_secret: ${{ secrets.SLACK_WEBHOOK_PATH }}
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: require('.github/scripts/labeled-pr.js')({github, context, SLACK_WEBHOOK_PATH})
