name: Pull Request Messenger
on:
  pull_request_target:
    types: [labeled]

jobs:
  comment:
    if: ${{github.action.pull_request.label.name == 'bug'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: require('.github/scripts/setup-pr.js')({github, context, core})
